export const LOAD_USER_START='LOAD_USER_START'
export const LOAD_USER_SUCCESS='LOAD_USER_SUCCESS'
export const LOAD_USER_ERROR='LOAD_USER_ERROR'

export const CREATE_USER_START='CREATE_USER_START'
export const CREATE_USER_SUCCESS='CREATE_USER_SUCCESS'
export const CREATE_USER_ERROR='CREATE_USER_ERROR'


export const CREATE_CURRICULUM = {
    "START":"CREATE_CURRICULUM_START",
    "SUCCESS":"CREATE_CURRICULUM_SUCCESS",
    "ERROR":"",
}

export const LOAD_CURRICULUM = {
    "START":"LOAD_CURRICULUM_START",
    "SUCCESS":"LOAD_CURRICULUM_SUCCESS",
    "ERROR": "LOAD_CURRICULUM_ERROR"
}

export const ENDPOINTS = {
    "USERS":"users",
    "CURRICULUM_TYPES":"curriculumTypes",
    "CURRICULUM":"curriculum"
}